// src/lib/components/sections/Contact.svelte
<script lang="ts">
  import SectionRoot from '$lib/components/sections/SectionRoot.svelte';
</script>

<SectionRoot heading="Contact">
  <p>
    <a
      class="text-blue-600 hover:underline"
      href="https://twitter.com/karukichi_yah"
      target="_blank"
      rel="noopener noreferrer"
    >
      TwitterのDM
    </a>
    までお願いします。
  </p>
</SectionRoot>

// src/components/sections/Contact.tsx
import React from 'react';
import SectionRoot from './SectionRoot';

const Contact: React.FC = () => {
  return (
    <SectionRoot heading="Contact">
      <p>
        <a
          className="text-blue-600 hover:underline"
          href="https://twitter.com/karukichi_yah"
          target="_blank"
          rel="noopener noreferrer"
        >
          TwitterのDM
        </a>
        までお願いします。
      </p>
    </SectionRoot>
  );
};

export default Contact;
