// src/lib/components/sections/Others.svelte
<script lang="ts">
	import SectionRoot from '$lib/components/sections/SectionRoot.svelte';
	import FaTwitter from 'svelte-icons/fa/FaTwitter.svelte';
	import FaGithub from 'svelte-icons/fa/FaGithub.svelte';
	import FaSpeakerDeck from 'svelte-icons/fa/FaSpeakerDeck.svelte';

	const INFOS = [
		{
			name: '@karukichi_yah',
			componentName: FaTwitter,
			url: 'https://twitter.com/karukichi_yah'
		},
		{
			name: 'GitHub',
			componentName: FaGithub,
			url: 'https://github.com/Yota-K'
		},
		{
			name: 'Speaker Deck',
			componentName: FaSpeakerDeck,
			url: 'https://speakerdeck.com/soejima0124'
		}
	] as const;
</script>

<SectionRoot heading="Others">
	<ul>
		{#each INFOS as info}
			<li class="items-center text-blue-600 last-of-type:pb-0">
				<a
					class="inline-block p-2 cursor-pointer font-bold hover:bg-blue-50 hover:rounded-lg"
					href={info.url}
					target="_blank"
					rel="noopener noreferrer"
				>
					<span class="inline-block align-middle pr-1 h-4">
						<svelte:component this={info.componentName} />
					</span>
					<span>{info.name}</span>
				</a>
			</li>
		{/each}
	</ul>
</SectionRoot>

// src/components/sections/Others.tsx
import React from 'react';
import SectionRoot from './SectionRoot';
import { FaTwitter, FaGithub, FaSpeakerDeck } from 'react-icons/fa';

const Others: React.FC = () => {
  const webInfoList = [
    {
      name: '@karukichi_yah',
      icon: <FaTwitter />,
      url: 'https://twitter.com/karukichi_yah',
    },
    {
      name: 'GitHub',
      icon: <FaGithub />,
      url: 'https://github.com/Yota-K',
    },
    {
      name: 'Speaker Deck',
      icon: <FaSpeakerDeck />,
      url: 'https://speakerdeck.com/soejima0124',
    },
  ];

  return (
    <SectionRoot heading="Others">
      <ul>
        {webInfoList.map((link) => (
          <li key={link.name} className="items-center text-blue-600 last-of-type:pb-0">
            <a
              className="inline-block p-2 cursor-pointer font-bold hover:bg-blue-50 hover:rounded-lg"
              href={link.url}
              target="_blank"
              rel="noopener noreferrer"
            >
              <span className="inline-block align-middle pr-2">{link.icon}</span>
              <span>{link.name}</span>
            </a>
          </li>
        ))}
      </ul>
    </SectionRoot>
  );
};

export default Others;
