// src/lib/components/Button.svelte
<script lang="ts">
	// `class` はJavaScriptの予約語なので、
	// 型キャストを使って `class` プロパティを作る
	let className: string;
	export { className as class };

	export let fontSize: string | null = null;
	export let fontWeight: string | null = null;
</script>

<button
	on:click
	class={`rounded-md px-4 py-2 ${fontSize === null ? 'text-sm' : fontSize} ${
		fontWeight === null ? 'font-medium' : fontWeight
	} transition-all duration-300 ${className}`}
>
	<slot />
</button>

// src/components/Button.tsx
import React from 'react';

type Props = {
  children: React.ReactNode;
} & Omit<React.ComponentPropsWithRef<'button'>, 'type'>;

const Button: React.FC<Props> = ({ children, className, ...rest }) => {
  return (
    <button
      type="button"
      className={`rounded-md px-4 py-2 text-sm font-medium transition-all duration-300 ${className}`}
      {...rest}
    >
      {children}
    </button>
  );
};

export default Button;
